In [ ]:
import numpy as np
a=np.arange(12)
print("a:\n",a)
b=a.reshape(3,4)
print("b:\n",b)
c=a.reshape(2,3,2)
print("c:\n",c)
d=a.reshape(3,-1)
print("d:\n",d)
e=a.reshape(1,-1)
print("e:\n",e)
flat=b.ravel()
print("flat:\n",flat)
flat2=b.flatten()
print("flatten:\n",flat2)
print("Transpose:\n",b.T)




a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
e:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
flat:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
features=np.array([1,2,3,4,5,6])
X=features.reshape(-1,1)
print("X:\n",X)

X:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
b=np.reshape(a,(3,4))
print("b:\n",b)
#print(np.reshape(2,3,2))
print(np.reshape(a,(-1,1)),np.reshape(a,(1,-1)))
print(np.reshape(a,(3,-1)),np.reshape(a,(-1,3)))
print(np.reshape(a,(3,4),order="C"))
print(np.reshape(a,(3,4),order="F"))


b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.reshape(a,(2,3))
print(b)
print(np.reshape(b,(3,-1)))
print(np.reshape(b,(-1,3)))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
zeros=np.zeros((1,3))
print("zeros:\n",zeros)
ones=np.ones((2,3))
print("ones:\n",ones)
range_arr=np.arange(0,10,2)
print("range:\n",range_arr)
rand=np.random.rand(3)
print("random of 3\n",rand)
randn=np.random.randn(3)
print("random of 3\n",randn)
rand_int=np.random.randint(0,10,3)
print("random integers of  3 between 0 to 10\n",rand_int)
rand1=np.random.random((2,2))
print("random numbers of matrix\n",rand1)
lin=np.linspace(0,1,5)
print("linspace of \n",lin)

[1 2 3 4]
zeros:
 [[0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
range:
 [0 2 4 6 8]
random of 3
 [0.94188673 0.37215522 0.02895592]
random of 3
 [-1.88664112  1.15442399 -1.06763535]
random integers of  3 between 0 to 10
 [9 9 2]
random numbers of matrix
 [[0.85315116 0.68190291]
 [0.59504815 0.40442478]]
linspace of 
 [0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
a=np.arange(12)
b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
print(b)
print(a+10)
#print(a+b)
print(b*3)
ones=np.ones((3,3))
print(ones*2)
c=b.flatten()
print(c)
print(a+c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[10 11 12 13 14 15 16 17 18 19 20 21]
[[ 3  6  9 12 15 18]
 [21 24 27 30 33 36]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a+10)
b=np.ones((3,3))
print(b)
c=np.array([1,2,3])
print(b+c)
col=np.array([[1],[2],[3]])
rows=np.array([10,20,30])
print(col+rows)
print(rows+col)

[[11 12 13]
 [14 15 16]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
import numpy as np
data=np.array([[1,2],[3,4],[5,6]])
print(data)
print("\n")
mean=data.mean(axis=0)
print(mean)
print("\n")
std=data.std(axis=0)
print(std)
print("\n")
normalized=(data-mean)/std
print(normalized)

[[1 2]
 [3 4]
 [5 6]]


[3. 4.]


[1.63299316 1.63299316]


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
import numpy as np
lin=np.linspace(0,100,10)
print("lin:\n",lin)
random=np.random.random((3,3))
print(random)
print(random.reshape(9,-1))


lin:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[[0.34973632 0.99226642 0.05434458]
 [0.39972175 0.48379909 0.83637028]
 [0.33692409 0.75052581 0.28279085]]
[[0.34973632]
 [0.99226642]
 [0.05434458]
 [0.39972175]
 [0.48379909]
 [0.83637028]
 [0.33692409]
 [0.75052581]
 [0.28279085]]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[2:])
print(mat[0:2,1:3])
print(arr+10)
print(arr*2)
print(mat+mat)
print(mat.sum())
print(mat.mean())
print(mat.max(axis=0))

[30 40 50 60]
[[2 3]
 [5 6]]
[20 30 40 50 60 70]
[ 20  40  60  80 100 120]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
45
5.0
[7 8 9]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[1][1])
print(mat[2])
print(mat[0:2,1:3])

5
[7 8 9]
[[2 3]
 [5 6]]


In [ ]:
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[mat>5])
print("sum per columns (axis=0)\n:",mat.sum(axis=0))
print("sum per rows (axis=1)\n:",mat.sum(axis=1))
print("mean per column:\n",mat.mean(axis=1))
mat[mat>5]=0
print(mat)

[6 7 8 9]
sum per columns (axis=0)
: [12 15 18]
sum per rows (axis=1)
: [ 6 15 24]
mean per column:
 [2. 5. 8.]
[[1 2 3]
 [4 5 0]
 [0 0 0]]


In [ ]:
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[mat%2==0])

[2 4 6 8]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([10,20,30])
print(a*10)
print(a+b)
print(a*b)
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat+100)
print(mat-1)
print(np.dot(a,b))

[10 20 30]
[11 22 33]
[10 40 90]
[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
140


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
mat=np.array([[1,2,3],[4,5,6]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.concatenate((a,b)))
arr=np.array([1,2,3,4,5,6])
print(np.split(arr,2))
print(np.split(arr,3))
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1@m2)
print(m1.T)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
import numpy as np
data=np.array([[80,90,70],[60,50,40],[100,95,90],[30,40,35],[70,75,80]])
print("original:\n",data)
norm=data/data.max()
print("normalied data:\n",norm)
print("avg marks per subject:\n",data.mean(axis=0))
print("total marks of all of each subject:\n ",data.sum(axis=0))
print("total of each studen:\n",data.sum(axis=1))
print("avg of each student:\n",data.mean(axis=1))
np.random.seed(0)
np.random.shuffle(data)
split=int(0.8 * len(data))
train,test=data[:split],data[split:]
print("Train:\n",train)
print("Test:\n",test)
print(len(data))


original:
 [[ 80  90  70]
 [ 60  50  40]
 [100  95  90]
 [ 30  40  35]
 [ 70  75  80]]
normalied data:
 [[0.8  0.9  0.7 ]
 [0.6  0.5  0.4 ]
 [1.   0.95 0.9 ]
 [0.3  0.4  0.35]
 [0.7  0.75 0.8 ]]
avg marks per subject:
 [68. 70. 63.]
total marks of all of each subject:
  [340 350 315]
total of each studen:
 [240 150 285 105 225]
avg of each student:
 [80. 50. 95. 35. 75.]
Train:
 [[100  95  90]
 [ 80  90  70]
 [ 60  50  40]
 [ 30  40  35]]
Test:
 [[70 75 80]]
5


In [ ]:
# 1. Clone your repo
!git clone https://github.com/rajeswaripallagani66-code/AI-ML-90-Day-Journey.git
%cd AI-ML-90-Day-Journey

# 2. Copy your current colab file into repo
!cp /content/your_notebook.py ./01-basics/06_train_test_split.py

# 3. Push (will ask GitHub username + token)
!git config --global user.email "your-email@gmail.com"
!git config --global user.name "rajeswari"
!git add .
!git commit -m "Day 1: NumPy train-test split + matmul completed"
!git push

Cloning into 'AI-ML-90-Day-Journey'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 36 (delta 7), reused 21 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 10.65 KiB | 3.55 MiB/s, done.
Resolving deltas: 100% (7/7), done.
/content/AI-ML-90-Day-Journey
cp: cannot stat '/content/your_notebook.py': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address


In [ ]:
# See what files you have
!ls
!ls 01-basics/

# Save your current notebook INTO your repo
!cp /content/drive/MyDrive/Colab\ Notebooks/Numpy.ipynb ./01-basics/ -OR-
# If your notebook is named Numpy.ipynb, just do:
!cp ../Numpy.ipynb ./01-basics/numpy_complete.ipynb

# Simpler: just save this current notebook file itself
%notebook Numpy.ipynb
!mv Numpy.ipynb ./01-basics/06_numpy_train_test_split.ipynb

!git add .
!git commit -m "Day 6: NumPy train-test + matmul added"
!git push


In [4]:
!git clone https://github.com/rajeswaripallagani66-code/AI-ML-90-Day-Journey.git
%cd AI-ML-90-Day-Journey

!pwd
%cd 01-basics
!ls

Cloning into 'AI-ML-90-Day-Journey'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 39 (delta 7), reused 21 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (39/39), 15.41 KiB | 15.41 MiB/s, done.
Resolving deltas: 100% (7/7), done.
/content/AI-ML-90-Day-Journey/AI-ML-90-Day-Journey/01-basics/AI-ML-90-Day-Journey
/content/AI-ML-90-Day-Journey/AI-ML-90-Day-Journey/01-basics/AI-ML-90-Day-Journey
/content/AI-ML-90-Day-Journey/AI-ML-90-Day-Journey/01-basics/AI-ML-90-Day-Journey/01-basics
day1.py  day2.py  day3.py  dsa1.py  dsa2.py  dsa.py


In [ ]:
!git clone https://github.com/rajeswaripallagani66-code/AI-ML-90-Day-Journey.git



!pwd
# should show /content/AI-ML-90-Day-Journey

%cd 01-basics
!pwd
# should show /content/AI-ML-90-Day-Journey/01-basics

!ls
# will show your files